apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}-php
  labels:
    app: {{ template "name" . }}-php
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.php.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-php
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: cloudsql-proxy
          secret:
            defaulMode: 420
            secretName: <SECRETNAME>
    spec:
      containers:
        - command:
          - /cloud_sql_proxy
          - --dir=/cloudsql
          - -credential_file=/secrets/cloudsql/credentials.json
          - -instances={{ .Values.gcloud_project_id }}:europe-west1:{{ .Values.db_name }}=tcp:5432
          image: b.gcr.io/cloudsql-docker/gce-proxy:1.13
          imagePullPolicy: Always
          name: cloudsql-proxy
          resources:
            requests:
              memory: "128M"
              cpu: "0.15"
            limits:
              memory: "1G"
              cpu: "0.15"
          volumeMounts:
            - mountPath: /secrets/cloudsql
              name: cloudsql-proxy
              readOnly: true

        - name: {{ .Chart.Name }}-php
          image: "{{ .Values.php.repository }}:{{ .Values.php.tag }}"
          imagePullPolicy: {{ .Values.php.pullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: debug
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: cors-allow-origin
            - name: VARNISH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: varnish-url
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-url
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
